# Generated by Django 6.0 on 2026-02-12 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='tasks/files/')),
            ],
        ),
        migrations.CreateModel(
            name='FillGapsTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('answers', models.JSONField(default=list)),
                ('list_type', models.CharField(choices=[('open', 'Открытый ввод'), ('hidden', 'Скрытый список слов')], default='open', max_length=20)),
                ('total_answers', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embed_code', models.TextField(verbose_name='Встроенный код')),
            ],
        ),
        migrations.CreateModel(
            name='MatchCardsTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cards', models.JSONField(default=list)),
                ('shuffled_cards', models.JSONField(default=list)),
                ('total_answers', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='NoteTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list)),
                ('total_answers', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TextInputTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(blank=True, max_length=255)),
                ('default_text', models.TextField(blank=True, verbose_name='Текст по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statements', models.JSONField(default=list)),
                ('total_answers', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='WordListTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('words', models.JSONField(default=list)),
                ('total_words', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(choices=[('original', 'Оригинал'), ('clone', 'Клон'), ('copy', 'Копия')], default='original', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('english', 'Английский'), ('other', 'Другое')], default='other', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('deactivated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_copies', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(choices=[('original', 'Оригинал'), ('clone', 'Клон'), ('copy', 'Копия')], default='original', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_copies', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(choices=[('original', 'Оригинал'), ('clone', 'Клон'), ('copy', 'Копия')], default='original', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.lesson')),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_copies', to='courses.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(choices=[('original', 'Оригинал'), ('clone', 'Клон'), ('copy', 'Копия')], default='original', max_length=20)),
                ('task_type', models.CharField(choices=[('test', 'Тест'), ('note', 'Заметка'), ('true_false', 'Правда или ложь'), ('fill_gaps', 'Заполнить пропуски'), ('match_cards', 'Соотнести карточки'), ('text_input', 'Ввод текста'), ('file', 'Файл'), ('word_list', 'Список слов')], db_index=True, max_length=50)),
                ('object_id', models.UUIDField(db_index=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_copies', to='courses.task')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['deactivated_at'], name='courses_cou_deactiv_7dbecc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['linked_to'], name='courses_cou_linked__68479c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['creator', 'root_type'], name='courses_cou_creator_9e40fd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['root_type', 'is_public'], name='courses_cou_root_ty_823f70_idx'),
        ),
    ]
