# Generated by Django 6.0 on 2026-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='root_type',
            field=models.CharField(choices=[('original', 'Оригинал'), ('clone', 'Клон'), ('copy', 'Копия')], default='original', help_text='Тип курса: оригинал, клон или копия', max_length=20),
        ),
    ]
