# Generated by Django 4.2.25 on 2025-10-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInputTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, max_length=255)),
                ('default_text', models.TextField(blank=True, verbose_name='Текст по умолчанию')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('test', 'Тест'), ('note', 'Заметка'), ('image', 'Изображение'), ('true_false', 'Правда или ложь'), ('fill_gaps', 'Заполнить пропуски'), ('match_cards', 'Соотнести карточки'), ('text_input', 'Ввод текста')], max_length=50),
        ),
    ]
