# Generated by Django 6.0 on 2026-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('english', 'Английский'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
