# Generated by Django 6.0 on 2026-01-29 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_root_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.URLField(max_length=1024)),
            ],
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['creator', 'root_type'], name='courses_cou_creator_9e40fd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['root_type', 'is_public'], name='courses_cou_root_ty_823f70_idx'),
        ),
    ]
