# Generated by Django 4.2.25 on 2025-11-04 09:56

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_textinputtask_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='image',
            field=models.ImageField(max_length=255, upload_to=courses.models.task_image_upload_to),
        ),
    ]
