# Generated by Django 6.0 on 2026-01-24 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.AddField(
            model_name='course',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='new_version_course',
            field=models.ForeignKey(blank=True, help_text='Новая версия этого курса, если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='original_course',
            field=models.ForeignKey(blank=True, help_text='Оригинальный курс, если это копия', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['deactivated_at'], name='courses_cou_deactiv_7dbecc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['original_course'], name='courses_cou_origina_3c8d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['new_version_course'], name='courses_cou_new_ver_507638_idx'),
        ),
    ]
