# Generated by Django 6.0 on 2026-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_filetask_course_courses_cou_creator_9e40fd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.JSONField(default=list)),
                ('total_words', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
