# Generated by Django 4.2.25 on 2025-11-14 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_imagetask_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillgapstask',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='matchcardstask',
            name='cards',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='TrueFalseTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('selected_value', models.BooleanField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_answers', to='courses.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_task_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextInputTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('current_text', models.TextField(blank=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_input_answers', to='courses.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_input_task_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='courses.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_task_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchCardsTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('selected_pairs', models.JSONField(default=list)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_cards_answers', to='courses.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_cards_task_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FillGapsTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=list)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_gaps_answers', to='courses.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_gaps_task_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='truefalsetaskanswer',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_truefalse_answer_per_user_task'),
        ),
        migrations.AddConstraint(
            model_name='textinputtaskanswer',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_textinput_answer_per_user_task'),
        ),
        migrations.AddConstraint(
            model_name='testtaskanswer',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_test_answer_per_user_task'),
        ),
        migrations.AddConstraint(
            model_name='matchcardstaskanswer',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_matchcards_answer_per_user_task'),
        ),
        migrations.AddConstraint(
            model_name='fillgapstaskanswer',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_fillgaps_answer_per_user_task'),
        ),
    ]
