# Generated by Django 6.0 on 2026-01-25 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_remove_course_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_new_ver_507638_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='new_version',
            field=models.ForeignKey(blank=True, help_text='Новая версия этого курса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_version', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['new_version'], name='courses_cou_new_ver_32dfc8_idx'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='new_version_course',
        ),
    ]
