# Generated by Django 4.2.25 on 2025-11-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_fillgapstask_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchcardstaskanswer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='matchcardstaskanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testtaskanswer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='testtaskanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textinputtaskanswer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='textinputtaskanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='truefalsetaskanswer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='truefalsetaskanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='FillGapsTaskAnswer',
        ),
        migrations.DeleteModel(
            name='MatchCardsTaskAnswer',
        ),
        migrations.DeleteModel(
            name='TestTaskAnswer',
        ),
        migrations.DeleteModel(
            name='TextInputTaskAnswer',
        ),
        migrations.DeleteModel(
            name='TrueFalseTaskAnswer',
        ),
    ]
