# Generated by Django 4.2.25 on 2025-11-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_matchcardstaskanswer_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcardstask',
            name='shuffled_cards',
            field=models.JSONField(default=list),
        ),
    ]
