# Generated by Django 6.0 on 2026-02-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_task_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillgapstask',
            old_name='task_type',
            new_name='list_type',
        ),
    ]
