# Generated by Django 4.2.25 on 2025-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_matchcardstask_shuffled_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtask',
            old_name='options',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='question',
        ),
        migrations.RemoveField(
            model_name='truefalsetask',
            name='is_true',
        ),
        migrations.RemoveField(
            model_name='truefalsetask',
            name='statement',
        ),
        migrations.AddField(
            model_name='truefalsetask',
            name='statements',
            field=models.JSONField(default=list),
        ),
    ]
