# Generated by Django 6.0 on 2026-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_task_type_fillgapstask_list_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetask',
            name='file_link',
        ),
        migrations.AddField(
            model_name='filetask',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
