# Generated by Django 4.2.25 on 2025-11-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_options_testtask_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_code', models.TextField(verbose_name='Встроенный код')),
            ],
        ),
    ]
