# Generated by Django 6.0 on 2026-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_filetask_file_link_filetask_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetask',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
