# Generated by Django 6.0 on 2026-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_filetask_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTask',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('test', 'Тест'), ('note', 'Заметка'), ('true_false', 'Правда или ложь'), ('fill_gaps', 'Заполнить пропуски'), ('match_cards', 'Соотнести карточки'), ('text_input', 'Ввод текста'), ('file', 'Файл'), ('word_list', 'Список слов')], db_index=True, max_length=50),
        ),
    ]
