# Generated by Django 4.2.25 on 2025-12-27 18:47

import classroom.utils.code_generation
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(default=classroom.utils.code_generation.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('invite_code', models.CharField(default=classroom.utils.code_generation.generate_invite_code, editable=False, max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='FillGapsTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MatchCardsTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('last_pair', models.JSONField(blank=True, null=True)),
                ('last_pair_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextInputTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('current_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseTaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('is_checked', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
    ]
