# Generated by Django 6.0 on 2026-01-27 15:40

import classroom.models.classroom
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('join_password', models.CharField(default=classroom.models.classroom.generate_join_password, help_text='пароль для входа в класс', max_length=12)),
                ('copying_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='FillGapsTaskAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MatchCardsTaskAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('last_pair', models.JSONField(blank=True, null=True)),
                ('last_pair_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTaskAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextInputTaskAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('current_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseTaskAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
