# Generated by Django 4.2.25 on 2025-11-04 10:01

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.CharField(default=classroom.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
