# Generated by Django 6.0 on 2026-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='join_password',
            field=models.CharField(default='', help_text='пароль для входа в класс', max_length=12),
        ),
    ]
