# Generated by Django 4.2.25 on 2025-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_truefalsetaskanswer_textinputtaskanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillgapstaskanswer',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='fillgapstaskanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='matchcardstaskanswer',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='matchcardstaskanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='matchcardstaskanswer',
            name='selected_pairs',
        ),
        migrations.RemoveField(
            model_name='textinputtaskanswer',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='matchcardstaskanswer',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fillgapstaskanswer',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
