# Generated by Django 4.2.25 on 2025-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_remove_fillgapstaskanswer_is_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtaskanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='testtaskanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='truefalsetaskanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='truefalsetaskanswer',
            name='selected_value',
        ),
        migrations.AddField(
            model_name='testtaskanswer',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='truefalsetaskanswer',
            name='answers',
            field=models.JSONField(default=list),
        ),
    ]
