# Generated by Django 4.2.25 on 2025-11-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_fillgapstaskanswer_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillgapstaskanswer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='matchcardstaskanswer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='testtaskanswer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='textinputtaskanswer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='truefalsetaskanswer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
