# Generated by Django 4.2.25 on 2025-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_fillgapstaskanswer_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcardstaskanswer',
            name='last_pair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchcardstaskanswer',
            name='last_pair_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
